cognitive-complexity-threshold = 30
too-many-arguments-threshold = 7

disallowed-methods = []

disallowed-names = ["foo", "bar", "baz"]

doc-valid-idents = [
    "LineGuard",
    "GitHub",
    "JSON",
]

enum-variant-name-threshold = 3
single-char-binding-names-threshold = 3
too-many-lines-threshold = 150
type-complexity-threshold = 250