coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 70%
        threshold: 3%
        base: auto

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: false
  hide_project_coverage: false

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: 75%
      - type: patch
        target: 70%

flags:
  unit-tests:
    carryforward: true
    statuses:
      - type: project
        target: 75%
      - type: patch
        target: 70%
  all-tests:
    carryforward: true
    statuses:
      - type: project
        target: 75%
      - type: patch
        target: 70%

ignore:
  - "tests/"
  - "**/*test*"
  - "**/test_*"
  - "**/*_test.rs"
  - "**/tests.rs"
  - "benches/"
  - "examples/"
