edition = "2024"
max_width = 100
use_small_heuristics = "Default"
match_block_trailing_comma = true
merge_derives = true
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true